<a href="https://colab.research.google.com/github/ilyosbek96/ai_foundation/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [7]:
print(pd.__version__)

2.2.3

In [9]:
mydataset = {
    'cars': ['BMS','VOLVO','FORD','MERCADES','TESLA','TOYOTA'],
    'counts': [3,7,2,4,5,1]
}

print(mydataset)
print("===================")

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMS', 'VOLVO', 'FORD', 'MERCADES', 'TESLA', 'TOYOTA'], 'counts': [3, 7, 2, 4, 5, 1]}
===================
       cars  counts
0       BMS       3
1     VOLVO       7
2      FORD       2
3  MERCADES       4
4     TESLA       5
5    TOYOTA       1

In [14]:
# head(malumotni oqib beradigon method) defaul xolatda 5tasini korsatadi
df.head(6) # -  qoyilsa 1tasini olib tashlaydi

       cars  counts
0       BMS       3
1     VOLVO       7
2      FORD       2
3  MERCADES       4
4     TESLA       5
5    TOYOTA       1

In [16]:
# tail(oxridan 5tasini olib beradi korsatadi)
df.tail()

       cars  counts
1     VOLVO       7
2      FORD       2
3  MERCADES       4
4     TESLA       5
5    TOYOTA       1

In [19]:
# shapePropertysi shapelarini korsatib beradi
df.shape

(6, 2)

In [20]:
# columns Propertysi columsbilan datatypesini olib beradi
df.columns

Index(['cars', 'counts'], dtype='object')

In [21]:
# dtypes xarbir colimslarni dtypesini korsatib beradi
df.dtypes

cars      object
counts     int64
dtype: object

In [22]:
# describe() numerical columns only
df.describe()

         counts
count  6.000000
mean   3.666667
std    2.160247
min    1.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    7.000000

In [27]:
df.iloc[2:]

       cars  counts
2      FORD       2
3  MERCADES       4
4     TESLA       5
5    TOYOTA       1

In [28]:
df.loc[:,'cars']

0         BMS
1       VOLVO
2        FORD
3    MERCADES
4       TESLA
5      TOYOTA
Name: cars, dtype: object

In [37]:
#1 df[df['counts'] >= 3]
df[df['cars'] == 'TESLA']

    cars  counts
4  TESLA       5

In [35]:
#1 df.mean(numeric_only=True)
df['counts'].mean()

np.float64(3.6666666666666665)

In [38]:
# sum(yigindisini chiqarib beradi)
df.sum()

cars      BMSVOLVOFORDMERCADESTESLATOYOTA
counts                                 22
dtype: object

In [39]:
# min(minimum raqamini chiqarib beradi)
df.min()

cars      BMS
counts      1
dtype: object

In [40]:
# max(eng kattasini olib beradi)
df.max()

cars      VOLVO
counts        7
dtype: object

In [41]:
# median(methodi defoul xolatda error qataradi shuning uchun numeric_only=True) yoziladi
df.median(numeric_only=True)

counts    3.5
dtype: float64

In [42]:
df.count()

cars      6
counts    6
dtype: int64

In [43]:
# std(standart divition)numeric_only=True yozilishi kerak
df.std(numeric_only=True)

counts    2.160247
dtype: float64

In [56]:

# isnull(tkshiradi bor bolsa tru yoki folse)
# sum(datasi yoqlarni olib beradi)

In [59]:
data_with_missing = {
    'cars': ['Bmw', 'Volvo', None, 'Tesla', 'Ferrari', None, "Ford"],
    'counts': [2, 5, None, 3, 1, 4, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      Bmw     2.0
1    Volvo     5.0
2     None     NaN
3    Tesla     3.0
4  Ferrari     1.0
5     None     4.0
6     Ford     NaN

In [60]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [64]:
# dropna(datalardagi yoq malumotlarni ochirish methodlari )
df_missing.dropna() # argument sifatida (how="all"nibersak qiymati borini chiqarib beradi) subset=[keni belgilasa yoq malumotni olib tashlaydi]

      cars  counts
0      Bmw     2.0
1    Volvo     5.0
3    Tesla     3.0
4  Ferrari     1.0

In [73]:
# fillna(malumoti yoq valuelarga berilga raqam yoki sozni qoyib qoyadi)
df_missing.fillna("yoq") # ({'cars': "yoq", 'counts': 0}) ikkinchi usul

      cars counts
0      Bmw    2.0
1    Volvo    5.0
2      yoq    yoq
3    Tesla    3.0
4  Ferrari    1.0
5      yoq    4.0
6     Ford    yoq

In [83]:
# df = pd.read_csv('Titanic-Dataset.csv')

df = pd.read_excel('test.xlsx')

df.head() # tail()

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [81]:
# import qilib olish
df.to_excel('test.xlsx')

In [84]:
# Series => 1D arraylar bilan ishlanadi
cars = pd.Series(['Bmw','Tesla','Ferrari'])
print(cars)

0        Bmw
1      Tesla
2    Ferrari
dtype: object

In [85]:
cars_series = data_with_missing['cars']
print(cars_series)

['Bmw', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']